Fix oauth2client redirectUri usage (#177)
This fixes the oauth2client usage warnings (
```
src/auth.ts(63,22): error TS2341: Property 'redirectUri' is private and only accessible within class 'OAuth2Client'.
src/auth.ts(80,18): error TS2341: Property 'redirectUri' is private and only accessible within class 'OAuth2Client'.
```
) by refactoring authorize functions and moves authorize into the auth module.

I've tested this change with the flows of clasp login / clasp login --no-localhost / clasp login --ownkey

With this, we'll be down to 0 build warnings! 🎉

- [x] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [x] Appropriate changes to README are included in PR.