Remove tsc errors and improve code quality (no implicity types, no double quotes).
Previous errors:
```
sudo npm run build;

> @google/clasp@1.3.0 build /Users/timmerman/Documents/github/google/clasp
> tsc --project tsconfig.json; npm i -g;

index.ts(200,17): error TS7006: Parameter 'answers' implicitly has an 'any' type.
index.ts(202,17): error TS7006: Parameter 'err' implicitly has an 'any' type.
index.ts(297,17): error TS7034: Variable 'fileIds' implicitly has type 'any[]' in some locations where its type cannot be determined.
index.ts(300,15): error TS7005: Variable 'fileIds' implicitly has an 'any[]' type.
index.ts(306,25): error TS7005: Variable 'fileIds' implicitly has an 'any[]' type.
index.ts(307,23): error TS7006: Parameter 'answers' implicitly has an 'any' type.
index.ts(312,23): error TS7006: Parameter 'err' implicitly has an 'any' type.
index.ts(714,25): error TS7017: Element implicitly has an 'any' type because type '{ textPayload: any; jsonPayload: any; protoPayload: any; }' has no index signature.
index.ts(720,31): error TS7017: Element implicitly has an 'any' type because type '{ ERROR: any; INFO: any; DEBUG: any; NOTICE: any; }' has no index signature.
index.ts(745,55): error TS7006: Parameter 'err' implicitly has an 'any' type.
index.ts(762,12): error TS7006: Parameter 'functionName' implicitly has an 'any' type.
src/auth.ts(63,55): error TS2339: Property 'port' does not exist on type 'string | AddressInfo'.
  Property 'port' does not exist on type 'string'.
/usr/local/bin/clasp -> /usr/local/lib/node_modules/@google/clasp/index.js
+ @google/clasp@1.3.0
added 1 package from 1 contributor in 2.725s
```

No errors now:
```
sudo npm run build
Password:
Sorry, try again.
Password:

> @google/clasp@1.3.1 build /Users/timmerman/Documents/github/google/clasp
> tsc --project tsconfig.json; npm i -g;

/usr/local/bin/clasp -> /usr/local/lib/node_modules/@google/clasp/index.js
+ @google/clasp@1.3.1
updated 1 package in 4.189s
```